### ISSUE TITLE
MJPEG 4:2:2 chroma recording/playback issue

### ISSUE THREAD

**Issue by r-sherwood** [seydx/homebridge-camera-ui#290]
**Describe the bug**
A recorded video from a MJPEG camera source (i.e. ESP32-CAM/TTGO T-CAMERA/...) fails to play in common browsers.
Firefox error message: "No video with supported format and MIME type found.

If I re-encode the recorded mp4 file with the following command, the video can be played without any issues.

`ffmpeg -i source_file.mp4 -pix_fmt yuv420p -b:v 4000k -c:v libx264 destination_file.mp4`

H264 videos expect a 4:4:4 chroma sampling which most MJPEG cameras don't support.

No issues with live videos from the same source.

**To Reproduce**
Record a video from a MJPEG camera source.
Playback the video through the camera-ui.

**Expected behavior**
Video should play in common browsers without issues.

**Screenshots**
![Screenshot 2021-11-17 at 10 55 59](https://user-images.githubusercontent.com/1226390/142182102-ada7f48b-25d6-4165-bb62-fcd342916e32.png)

**Environment**
- Node.js Version: v14.18.1
- Homebridge Version: v1.3.6
- Camera UI Version: v4.2.10
- Operating System: raspberry debian buster
- Browser: Firefox Max 93.0 (64 bit)

**Comment by r-sherwood** [comment]
Best settings I could achieve for recordings straight from the source on a raspberry pi 3B including video hardware acceleration: 
`ffmpeg -f mjpeg -nostdin -y -i http://ESP32-CAM-SOURCE/mjpeg/1 -hide_banner -loglevel error -t 10 -strict experimental -threads 0 -c:v h264_v4l2m2m -pix_fmt yuv420p -b:v 2M -s 1280x720 -movflags +faststart -crf 23 DESTINATION-FILE.mp4`

I've adapted these settings in /homebridge-camera-ui/server/services/ffmpeg.service.js:
...
ffmpegArguments +=
  ' -hide_banner -loglevel error' +
  ' -t ${recTimer}' +
  (videoFilter ? ' -filter:v ' + videoFilter : '') +
  ' -strict experimental' +
  ' -threads 0' +
  **' -c:v h264_v4l2m2m' +
  ' -pix_fmt yuv420p' +
  ' -b:v 2M' +**
  ' -s ${width}x${height}' +
  ' -movflags +faststart' +
  ' -crf 23 ' +
  videoName;
...

**Comment by seydx** [comment]
Hey thx for the feedback, added a fix to v5 (beta) which is completely redesigned and refactored

wanna give it a try?

``sudo npm i -g homebridge-camera-ui@beta``

**Comment by r-sherwood** [comment]
New version looking good so far. No issues with streaming video through the web-ui and homekit.
But I'm not able to get a video recorded.


[18/12/2021, 10:41:59] [CameraUI] ESP32-Cam-Stairwell: Dorbell ON
[18/12/2021, 10:41:59] [CameraUI] ESP32-Cam-Stairwell: Handling event: Doorbell switched on
[18/12/2021, 10:41:59] [CameraUI] Received a new MQTT message {"error":false,"message":"Handled through extern controller"} (ESP32-Cam-Stairwell)
[18/12/2021, 10:41:59] [CameraUI] ESP32-Cam-Stairwell: Dorbell ON
[18/12/2021, 10:41:59] [CameraUI] ESP32-Cam-Stairwell: Handling event: Skip doorbell event, timeout active!
[18/12/2021, 10:41:59] [CameraUI] Received a new MQTT message {"error":false,"message":"Skip motion event, timeout active!"} (ESP32-Cam-Stairwell)
[18/12/2021, 10:42:00] [CameraUI] ESP32-Cam-Stairwell: Snapshot requested: 1280 x 720
[18/12/2021, 10:42:00] [CameraUI] ESP32-Cam-Stairwell: Snapshot command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i http://[IP]/jpg -frames:v 1 -f image2 - -hide_banner -loglevel error
[18/12/2021, 10:42:00] [CameraUI] ESP32-Cam-Stairwell: New doorbell alert
[18/12/2021, 10:42:00] [CameraUI] Skip interface notification
[18/12/2021, 10:42:00] [CameraUI] ESP32-Cam-Stairwell: An error occured during handling motion event
[18/12/2021, 10:42:00] [CameraUI] TypeError: Cannot destructure property 'notification' of '(intermediate value)' as it is undefined.
[18/12/2021, 10:42:00] [CameraUI] ESP32-Cam-Stairwell: [mjpeg @ 0x438ad70] error dc[mjpeg @ 0x438ad70] error y=89 x=79


The error `Cannot destructure property 'notification' of '(intermediate value)' as it is undefined.` pops up in the UI as well.
How can I solve the timeout issues?




BTW: there is a typo in the first log row "Dorbell ON", should be "Doorbell ON"

**Comment by seydx** [comment]
Can u post your config.json pls

**Comment by r-sherwood** [comment]
Here is the relevant CamerUI part:

        {
            "name": "CameraUI",
            "port": 8181,
            "atHomeSwitch": false,
            "debug": true,
            "mqtt": {
                "active": true,
                "tls": false,
                "host": "127.0.0.1",
                "port": 1883,
                "username": "XXX",
                "password": "XXX"
            },
            "http": {
                "active": false,
                "port": 8282,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ssl": {
                "active": true,
                "key": "/tmp/privkey10.pem",
                "cert": "/tmp/fullchain10.pem"
            },
            "cameras": [
                {
                    "name": "ESP32-Cam-Stairwell",
                    "manufacturer": "espressif",
                    "model": "ESP32-Cam",
                    "motion": true,
                    "doorbell": true,
                    "switches": false,
                    "motionTimeout": 60,
                    "motionDoorbell": false,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-f mjpeg -i http://[IP]/mjpeg/1",
                        "stillImageSource": "-i http://[IP]/jpg",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 4000,
                        "forceMax": true,
                        "vcodec": "h264_v4l2m2m",
                        "stimeout": "",
                        "debug": true
                    },
                    "mqtt": {
                        "motionTopic": "mqttGenericBridge/AlarmEscalation/state",
                        "motionMessage": "on",
                        "doorbellTopic": "mqttGenericBridge/EingangstuerA_S3/state",
                        "doorbellMessage": "closed"
                    },
                    "hsv": false
                },
                {
                    "name": "ESP32-Cam-Passage",
                    "manufacturer": "espressif",
                    "model": "ESP32-Cam",
                    "motion": true,
                    "doorbell": false,
                    "switches": false,
                    "motionTimeout": 60,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-f mjpeg -i http://[IP]/mjpeg/1",
                        "stillImageSource": "-i http://[IP]/jpg",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 4000,
                        "forceMax": true,
                        "vcodec": "h264_v4l2m2m",
                        "stimeout": 0,
                        "debug": false
                    },
                    "mqtt": {
                        "motionTopic": "mqttGenericBridge/AlarmEscalation/state",
                        "motionMessage": "on"
                    },
                    "hsv": false
                }
            ],
            "platform": "CameraUI"
        },

**Comment by seydx** [comment]
Can you open the camera.ui web interface > console and attach the log from the camera.ui console please. (From start up till motion detection)

**Comment by seydx** [comment]
@r-sherwood 

should be fixed in v5.0.0-beta.27

``sudo npm i -g homebridge-camera-ui@5.0.0-beta.27``

**Comment by r-sherwood** [comment]
Unfortunately it's not fixed and recordings are still not possible under v5.0.0-beta.32.
I'll update with some logs soon.

**Comment by seydx** [comment]
can u try v5.0.0-beta.37 pls

**Comment by r-sherwood** [comment]
Tested on v5.0.0-beta.37

Some timeout issues now?



[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Doorbell ON
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Handling event: Doorbell switched on
[29/12/2021, 17:32:16] [CameraUI] MQTT: Received a new message {"error":false,"message":"Handled through intern controller"} (ESP32-Cam-Stairwell)
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: New doorbell alert
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Skip Webhook notification
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Skip alexa notification
[29/12/2021, 17:32:16] [CameraUI] Skip recording
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Skip Webpush notification
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Recording skipped. Notification skipped.
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Doorbell ON (Skip doorbell event, timeout active)
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Handling event: Skip doorbell event, timeout active!
[29/12/2021, 17:32:16] [CameraUI] MQTT: Received a new message {"error":false,"message":"Handled through intern controller - Skip motion event, timeout active!"} (ESP32-Cam-Stairwell)
[29/12/2021, 17:32:17] [CameraUI] ESP32-Cam-Stairwell: Fetching snapshot took 1.176 seconds.
[29/12/2021, 17:32:17] [CameraUI] ESP32-Cam-Stairwell: Sending snapshot: 1280x720
[29/12/2021, 17:32:17] [CameraUI] ESP32-Cam-Stairwell: Resize command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[29/12/2021, 17:32:28] [CameraUI] ESP32-Cam-Stairwell: Snapshot requested: 1280 x 720
[29/12/2021, 17:32:28] [CameraUI] ESP32-Cam-Stairwell: Snapshot command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -i http://[IP]/jpg -frames:v 1 -f image2 -
[29/12/2021, 17:32:28] [CameraUI] ESP32-Cam-Stairwell: Fetching snapshot took 0.702 seconds.
[29/12/2021, 17:32:28] [CameraUI] ESP32-Cam-Stairwell: Sending snapshot: 1280x720
[29/12/2021, 17:32:28] [CameraUI] ESP32-Cam-Stairwell: Resize command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[29/12/2021, 17:32:39] [CameraUI] ESP32-Cam-Stairwell: Snapshot requested: 1280 x 720
[29/12/2021, 17:32:39] [CameraUI] ESP32-Cam-Stairwell: Snapshot command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -i http://[IP]/jpg -frames:v 1 -f image2 -
[29/12/2021, 17:32:39] [CameraUI] ESP32-Cam-Stairwell: Fetching snapshot took 0.471 seconds.
[29/12/2021, 17:32:39] [CameraUI] ESP32-Cam-Stairwell: Sending snapshot: 1280x720
[29/12/2021, 17:32:39] [CameraUI] ESP32-Cam-Stairwell: Resize command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[29/12/2021, 17:32:49] [CameraUI] ESP32-Cam-Stairwell: Snapshot requested: 1280 x 720
[29/12/2021, 17:32:49] [CameraUI] ESP32-Cam-Stairwell: Snapshot command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -i http://[IP]/jpg -frames:v 1 -f image2 -
[29/12/2021, 17:32:50] [CameraUI] ESP32-Cam-Stairwell: Fetching snapshot took 0.737 seconds.
[29/12/2021, 17:32:50] [CameraUI] ESP32-Cam-Stairwell: Sending snapshot: 1280x720
[29/12/2021, 17:32:50] [CameraUI] ESP32-Cam-Stairwell: Resize command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[29/12/2021, 17:33:00] [CameraUI] ESP32-Cam-Stairwell: Snapshot requested: 1280 x 720
[29/12/2021, 17:33:00] [CameraUI] ESP32-Cam-Stairwell: Snapshot command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -i http://[IP]/jpg -frames:v 1 -f image2 -
[29/12/2021, 17:33:01] [CameraUI] ESP32-Cam-Stairwell: Fetching snapshot took 0.647 seconds.
[29/12/2021, 17:33:01] [CameraUI] ESP32-Cam-Stairwell: Sending snapshot: 1280x720
[29/12/2021, 17:33:01] [CameraUI] ESP32-Cam-Stairwell: Resize command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[29/12/2021, 17:33:11] [CameraUI] ESP32-Cam-Stairwell: Snapshot requested: 1280 x 720
[29/12/2021, 17:33:11] [CameraUI] ESP32-Cam-Stairwell: Snapshot command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -loglevel error -i http://[IP]/jpg -frames:v 1 -f image2 -
[29/12/2021, 17:33:12] [CameraUI] ESP32-Cam-Stairwell: Fetching snapshot took 0.753 seconds.
[29/12/2021, 17:33:12] [CameraUI] ESP32-Cam-Stairwell: Sending snapshot: 1280x720
[29/12/2021, 17:33:12] [CameraUI] ESP32-Cam-Stairwell: Resize command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
[29/12/2021, 17:33:16] [CameraUI] ESP32-Cam-Stairwell: Doorbell handler timeout.
[29/12/2021, 17:33:16] [CameraUI] ESP32-Cam-Stairwell: Motion handler timeout. (ui)

**Comment by seydx** [comment]
Everything working fine, there is a minimum timeout of 15s to handle motion events. So every motion alert within 15s will be skipped to avoid multiple recordings at same time.

to get notification or recording you need to enable them in the camera.ui interface

**Comment by r-sherwood** [comment]
But there are no recording files in the specified directory. 

A notification of the movement appears under Notifications, but clicking on them brings a similar picture like in the first post.
I can't see any ffmpeg process to analyses the settings.

**Comment by seydx** [comment]
As you can see here

```
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Skip Webhook notification
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Skip alexa notification
[29/12/2021, 17:32:16] [CameraUI] Skip recording
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Skip Webpush notification
[29/12/2021, 17:32:16] [CameraUI] ESP32-Cam-Stairwell: Recording skipped. Notification skipped.
```

Recording is not enabled in the camera.ui settings

open the camera.ui interface, navigate to settings > recordings, and enable recordings

**Comment by r-sherwood** [comment]
There we go.
Guess the setting was lost during updates.

Issue solved.
Thanks

**Comment by seydx** [comment]
An upgrade from v4 to v5 rebuild the database and resetted all your settings
