### ISSUE TITLE
HSV Recordings being aborted with "undefined"

### ISSUE THREAD

**Issue by bravesfan171** [seydx/homebridge-camera-ui#382]
Trying to setup motion recordings through MQTT payloads. MQTT is being received just fine, but I get notifications through the HomeKit with just a still image snapshot (no video) and no recording is created in HomeKit for the event either. See the log below for the error as to why it doesn't record. Have tried a number of things in the config but haven't had any luck. 

> [1/21/2022, 10:44:25 PM] [CameraUI] MQTT: New message: Topic: backyard - Data: ON - Type: string
[1/21/2022, 10:44:25 PM] [CameraUI] Backyard: Motion ON
[1/21/2022, 10:44:45 PM] [CameraUI] Backyard: Motion OFF - Motion handler timeout.
[1/21/2022, 10:44:47 PM] [CameraUI] Backyard: The recording process was aborted by HSV with reason "undefined"
[1/21/2022, 10:44:47 PM] [CameraUI] Backyard: Closing recording process

Full config:
>{
  "name": "CameraUI",
  "port": 8081,
  "atHomeSwitch": false,
  "debug": false,
  "mqtt": {
    "active": true,
    "host": "192.168.1.101",
    "username": "mqtt",
    "password": "mqtt"
  },
  "http": {
    "active": false
  },
  "smtp": {
    "active": false
  },
  "ftp": {
    "active": false
  },
  "ssl": {
    "active": false
  },
  "cameras": [
    {
    {
      "name": "Backyard",
      "manufacturer": "Unifi",
      "model": "G4 Bullet",
      "motion": true,
      "switches": false,
      "useInterfaceTimer": false,
      "motionTimeout": 20,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4000,
      "videoConfig": {
        "source": "-i URL",
        "subSource": "-i URL",
        "stillImageSource": "-i URL",
        "rtspTransport": "tcp",
        "maxStreams": 3,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": true,
        "debug": true
      },
      "mqtt": {
        "motionTopic": "backyard",
        "motionMessage": "ON",
        "motionResetTopic": "backyard",
        "motionResetMessage": "OFF"
      },
      "smtp": {
        "email": "Backyard"
      },
      "videoanalysis": {
        "active": false
      }
    },
  ],
  "options": {
    "videoProcessor": "ffmpeg"
  }
}

**Comment by cteubank** [comment]
I'm seeing a similar issue w/ SMTP motion triggering on an Annke C800

**Comment by seydx** [comment]
fixed in v5.0.11

**Comment by bravesfan171** [comment]
@seydx so it’s not logging the error anymore, but the issue still persists and I can’t figure out why. The MQTT message triggers a motion event but there is no recording saved in in HomeKit and the motion notification from HomeKit doesn’t show a video, just a still image. Any ideas?

**Comment by seydx** [comment]
> @seydx so it’s not logging the error anymore, but the issue still persists and I can’t figure out why. The MQTT message triggers a motion event but there is no recording saved in in HomeKit and the motion notification from HomeKit doesn’t show a video, just a still image. Any ideas?

Can you enable debug in your config.json, trigger s movement and send me the whole log pls (also install the latest version of camera ui)

**Comment by Tombra1889** [comment]
Is 'The recording process was aborted by HSV with reason "UNEXPECTED_FAILURE"' the same problem?

**Comment by seydx** [comment]
@Tombra1889 

no, its related to a wrong config.json and/or camera config

Can you post your config.json and a screenshot from the cameras own settings (like fps, resolution, bitrate etc)

**Comment by Tombra1889** [comment]
thx. that's my new settings:
![image](https://user-images.githubusercontent.com/60692414/150646147-86c8227e-d032-4206-a636-669719343895.png)


{
            "name": "CameraUI",
            "port": 8583,
            "debug": true,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": true,
                "port": 8582,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Entry",
                    "manufacturer": "INSTAR",
                    "model": "N-5907HD-PoE",
                    "motion": true,
                    "doorbell": true,
                    "useInterfaceTimer": false,
                    "motionTimeout": 60,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://xxxxx:xxxxx@192.168.66.191/11",
                        "subSource": "-i rtsp://xxxxx:xxxxx@192.168.66.191/12",
                        "stillImageSource": "-i http://192.168.66.191/tmpfs/snap.jpg?usr=xxxxx&pwd=xxxxx",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "acodec": "copy",
                        "stimeout": 10,
                        "audio": false,
                        "debug": true
                    },
                    "videoanalysis": {
                        "active": false
                    }
                }

**Comment by seydx** [comment]
@Tombra1889 

try with a lower image quality and bitrate (eg 2048 kbps)

**Comment by Tombra1889** [comment]
same problem :-/

**Comment by seydx** [comment]
> same problem :-/

Set vcodec to `"libx264"`

**Comment by Tombra1889** [comment]
the crazy thing is that it works partially with Keyframe = 20.

[22/01/2022, 17:10:41] [CameraUI] Entry: Motion ON
[22/01/2022, 17:10:42] [CameraUI] Entry: Video fragments requested from HSV
[22/01/2022, 17:10:42] [CameraUI] Entry: Setting prebuffer stream as input
[22/01/2022, 17:10:42] [CameraUI] Entry: Prebuffer requested with a duration of -4s
[22/01/2022, 17:10:42] [CameraUI] Entry: Start recording...
[22/01/2022, 17:10:42] [CameraUI] Entry: Recording command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -analyzeduration 0 -probesize 1822588 -f mp4 -i tcp://127.0.0.1:30820 -f mp4 -sn -dn -vcodec libx264 -pix_fmt yuv420p -profile:v baseline -level:v 3.1 -b:v 2000k -vf fps=30,scale=w=1920:h=1080:force_original_aspect_ratio=1,pad=1920:1080:(ow-iw)/2:(oh-ih)/2 -force_key_frames expr:gte(t,n_forced*4) -an -movflags frag_keyframe+empty_moov+default_base_moof -max_muxing_queue_size 1024 tcp://127.0.0.1:30834
[22/01/2022, 17:10:42] [CameraUI] Entry: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tcp://127.0.0.1:30820':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf58.45.100
  Duration: 00:00:16.43, start: 8.300000, bitrate: N/A

[22/01/2022, 17:10:42] [CameraUI] Entry:     Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuvj420p(pc), 1280x720, 886 kb/s, 12.15 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler

[22/01/2022, 17:10:42] [CameraUI] Entry: Recording started
[22/01/2022, 17:10:42] [CameraUI] Entry: Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help

[22/01/2022, 17:10:42] [CameraUI] Entry: [swscaler @ 0x29f92e0] deprecated pixel format used, make sure you did set range correctly

[22/01/2022, 17:10:42] [CameraUI] Entry: [libx264 @ 0x29cffc0] frame MB size (120x68) > level limit (3600)
[libx264 @ 0x29cffc0] MB rate (244800) > level limit (108000)

[22/01/2022, 17:10:42] [CameraUI] Entry: [libx264 @ 0x29cffc0] using cpu capabilities: ARMv6 NEON

[22/01/2022, 17:10:42] [CameraUI] Entry: [libx264 @ 0x29cffc0] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x29cffc0] 
[22/01/2022, 17:10:42] [CameraUI] Entry: 264 - core 160 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=2 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=2000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'tcp://127.0.0.1:30834':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf58.45.100

[22/01/2022, 17:10:42] [CameraUI] Entry:     Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1920x1080, q=-1--1, 2000 kb/s, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/2000000 buffer size: 0 vbv_delay: N/A

[22/01/2022, 17:10:42] [CameraUI] Entry: frame=   12 fps=0.0 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
[22/01/2022, 17:10:43] [CameraUI] Entry: frame=   21 fps= 18 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
[22/01/2022, 17:10:44] [CameraUI] Entry: frame=   33 fps= 19 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
[22/01/2022, 17:10:45] [CameraUI] Entry: frame=   48 fps= 16 q=36.0 size=       1kB time=00:00:00.00 bitrate=93046.2kbits/s speed=2.17e-05x    
[22/01/2022, 17:10:45] [CameraUI] Entry: frame=   55 fps= 16 q=40.0 size=       1kB time=00:00:00.23 bitrate=  25.9kbits/s speed=0.0661x    
[22/01/2022, 17:10:46] [CameraUI] Entry: frame=   64 fps= 16 q=33.0 size=       1kB time=00:00:00.53 bitrate=  11.3kbits/s speed=0.132x    
[22/01/2022, 17:10:46] [CameraUI] Entry: frame=   74 fps= 16 q=33.0 size=       1kB time=00:00:00.86 bitrate=   7.0kbits/s speed=0.184x    
[22/01/2022, 17:10:47] [CameraUI] Entry: frame=   84 fps= 16 q=32.0 size=       1kB time=00:00:01.20 bitrate=   5.0kbits/s speed=0.229x    
[22/01/2022, 17:10:48] [CameraUI] Entry: frame=   93 fps= 16 q=31.0 size=       1kB time=00:00:01.50 bitrate=   4.0kbits/s speed=0.255x    
[22/01/2022, 17:10:48] [CameraUI] Entry: frame=  103 fps= 16 q=31.0 size=       1kB time=00:00:01.83 bitrate=   3.3kbits/s speed=0.283x    
[22/01/2022, 17:10:49] [CameraUI] Entry: frame=  112 fps= 16 q=30.0 size=       1kB time=00:00:02.13 bitrate=   2.8kbits/s speed=0.302x    
[22/01/2022, 17:10:50] [CameraUI] Entry: frame=  122 fps= 16 q=30.0 size=       1kB time=00:00:02.46 bitrate=   2.5kbits/s speed=0.319x    
[22/01/2022, 17:10:50] [CameraUI] Entry: frame=  132 fps= 16 q=30.0 size=       1kB time=00:00:02.80 bitrate=   2.2kbits/s speed=0.338x    
[22/01/2022, 17:10:51] [CameraUI] Entry: Closing recording process
[22/01/2022, 17:10:51] [CameraUI] Entry: Resetting motion sensor, because HSV closed the recording process
[22/01/2022, 17:10:51] [CameraUI] Entry: FFMPEG socket closed during read for 8 bytes!
[22/01/2022, 17:10:51] [CameraUI] Entry: The recording process was aborted by HSV with reason "CANCELLED"
[22/01/2022, 17:10:51] [CameraUI] Entry: Prebuffer request ended
[22/01/2022, 17:10:51] [CameraUI] Entry: FFmpeg recording process exited (expected)

**Comment by seydx** [comment]
> thx. that's my new settings: ![image](https://user-images.githubusercontent.com/60692414/150646147-86c8227e-d032-4206-a636-669719343895.png)
> 
> { "name": "CameraUI", "port": 8583, "debug": true, "mqtt": { "active": false }, "http": { "active": true, "port": 8582, "localhttp": false }, "smtp": { "active": false }, "ftp": { "active": false }, "ssl": { "active": false }, "cameras": [ { "name": "Entry", "manufacturer": "INSTAR", "model": "N-5907HD-PoE", "motion": true, "doorbell": true, "useInterfaceTimer": false, "motionTimeout": 60, "unbridge": true, "hsv": true, "prebuffering": true, "prebufferLength": 4, "videoConfig": { "source": "-i rtsp://xxxxx:xxxxx@192.168.66.191/11", "subSource": "-i rtsp://xxxxx:xxxxx@192.168.66.191/12", "stillImageSource": "-i http://192.168.66.191/tmpfs/snap.jpg?usr=xxxxx&pwd=xxxxx", "rtspTransport": "tcp", "maxStreams": 2, "vcodec": "copy", "acodec": "copy", "stimeout": 10, "audio": false, "debug": true }, "videoanalysis": { "active": false } }

Change „Video-Encoding“ (camera settings) to Constant Bitrate

**Comment by Tombra1889** [comment]
Garten: The recording process was aborted by HSV with reason "UNEXPECTED_FAILURE"

**Comment by seydx** [comment]
> The recording process was aborted by HSV with reason "UNEXPECTED_FAILURE"

Hmm weird

Try with following camera settings

Resolution: 1280x720
FPS: 30
Keyframe Interval: 120
Image Quality: 3
Bitrate: 2048 kbps
Video Encoding: Constant Bitrate (CBR) or None

config.json

```json

{
  "name": "CameraUI",
  "port": 8583,
  "debug": true,
  "mqtt": {
    "active": false
  },
  "http": {
    "active": true,
    "port": 8582,
    "localhttp": false
  },
  "smtp": {
    "active": false
  },
  "ftp": {
    "active": false
  },
  "ssl": {
    "active": false
  },
  "cameras": [
    {
      "name": "Entry",
      "manufacturer": "INSTAR",
      "model": "N-5907HD-PoE",
      "motion": true,
      "doorbell": true,
      "useInterfaceTimer": false,
      "motionTimeout": 60,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://xxxxx:xxxxx@192.168.66.191/11",
        "subSource": "-i rtsp://xxxxx:xxxxx@192.168.66.191/12",
        "stillImageSource": "-i http://192.168.66.191/tmpfs/snap.jpg?usr=xxxxx&pwd=xxxxx",
        "rtspTransport": "tcp",
        "maxStreams": 4,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": false,
        "debug": true
      },
      "videoanalysis": {
        "active": false
      }
    }
  ]
}
```

**Comment by Tombra1889** [comment]
25 fps is the max

**Comment by bravesfan171** [comment]
@seydx here's the result with debug on. The backyard event was the one I triggered. So the motion event is being triggered and it actually _does_ record the event in HSV. But for some reason, the notification the app sends is just a still image instead of video clip like if the video analysis was on and it triggers based on motion on the substream. Any ideas?
```
[1/22/2022, 2:53:16 PM] Homebridge v1.4.0 (HAP v0.10.0) (CameraUI) is running on port 53011.
[1/22/2022, 2:53:27 PM] [CameraUI] Front Door: Setting up camera, please be patient...
[1/22/2022, 2:53:27 PM] [CameraUI] Backyard: Setting up camera, please be patient...
[1/22/2022, 2:53:27 PM] [CameraUI] Driveway: Setting up camera, please be patient...
[1/22/2022, 2:53:27 PM] [CameraUI] Front Porch: Setting up camera, please be patient...
[1/22/2022, 2:53:27 PM] [CameraUI] Front Yard: Setting up camera, please be patient...
[1/22/2022, 2:53:27 PM] [CameraUI] Grayson’s Room: Setting up camera, please be patient...
[1/22/2022, 2:53:27 PM] [CameraUI] Levi’s Room: Setting up camera, please be patient...
[1/22/2022, 2:53:27 PM] [CameraUI] Playroom: Setting up camera, please be patient...
[1/22/2022, 2:53:28 PM] [CameraUI] Grayson’s Room: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:28 PM] [CameraUI] Playroom: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:28 PM] [CameraUI] Levi’s Room: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:28 PM] [CameraUI] Front Door: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:29 PM] [CameraUI] Front Yard: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:29 PM] [CameraUI] Front Porch: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:29 PM] [CameraUI] Driveway: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:29 PM] [CameraUI] Backyard: Prebuffering scheduled for restart at 2AM: 667 minutes
[1/22/2022, 2:53:29 PM] [CameraUI] Front Door: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Front Door: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Backyard: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Backyard: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Driveway: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Driveway: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Front Porch: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Front Porch: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Front Yard: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Front Yard: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Grayson’s Room: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Grayson’s Room: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Levi’s Room: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Levi’s Room: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Playroom: Configuring unbridged accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] Playroom: Setting up accessory...
[1/22/2022, 2:53:29 PM] [CameraUI] camera.ui v5.0.12 is listening on port 8081 (http)
[1/22/2022, 2:53:29 PM] Front Door 8035 is running on port 39391.
[1/22/2022, 2:53:29 PM] Please add [Front Door 8035] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 2:53:29 PM] Backyard 313D is running on port 46005.
[1/22/2022, 2:53:29 PM] Please add [Backyard 313D] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 2:53:29 PM] Driveway DDE6 is running on port 45709.
[1/22/2022, 2:53:29 PM] Please add [Driveway DDE6] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 2:53:29 PM] Front Porch 6EAB is running on port 44923.
[1/22/2022, 2:53:29 PM] Please add [Front Porch 6EAB] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 2:53:29 PM] Front Yard AB66 is running on port 39035.
[1/22/2022, 2:53:29 PM] Please add [Front Yard AB66] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 2:53:29 PM] Grayson’s Room FCF2 is running on port 43917.
[1/22/2022, 2:53:29 PM] Please add [Grayson’s Room FCF2] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 2:53:29 PM] Levi’s Room 636D is running on port 34271.
[1/22/2022, 2:53:29 PM] Please add [Levi’s Room 636D] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 2:53:29 PM] Playroom 5F1C is running on port 45899.
[1/22/2022, 2:53:29 PM] Please add [Playroom 5F1C] manually in Home app. Setup Code: 031-45-154
[1/22/2022, 3:42:26 PM] [CameraUI] Config changed through interface, saving...
[1/22/2022, 3:42:26 PM] [CameraUI] Accessories refreshed and config.json saved!
[1/22/2022, 3:42:42 PM] [CameraUI] Front Door: Unknown target specified for motion handler (custom)!
[1/22/2022, 3:43:23 PM] [CameraUI] MQTT: New message: Topic: backyard - Data: ON - Type: string
[1/22/2022, 3:43:23 PM] [CameraUI] Backyard: Motion ON
[1/22/2022, 3:43:43 PM] [CameraUI] Backyard: Motion OFF - Motion handler timeout.
[1/22/2022, 3:43:45 PM] [CameraUI] Backyard: Closing recording process
```
