### ISSUE TITLE
Camera always offline on CameraUI/cameras or CamView but recordings and notifications working

### ISSUE THREAD

**Issue by rashmendis** [SeydX/homebridge-camera-ui#98]
The camera always offline on CameraUI/Cameras, CameraUI/Dashboard, or CameraUI/CamView but recordings and notifications working. The camera feed and still photos working on the Home app as well. Tested on Firefox, Chromium, and Safari browsers.

`{
            "name": "CameraUI",
            "port": 8181,
            "auth": "form",
            "debug": true,
            "reset": false,
            "http": {
                "active": false,
                "port": 7777,
                "localhttp": false
            },
            "options": {
                "videoProcessor": "ffmpeg"
            },
            "cameras": [
                {
                    "name": "Camera1",
                    "motion": true,
                    "switches": true,
                    "doorbell": true,
                    "motionTimeout": 5,
                    "videoConfig": {
                        "source": "-i http://192.168.1.31/mjpeg/1",
                        "stillImageSource": "-i http://192.168.1.31/jpg",
                        "maxStreams": 5,
                        "maxHeight": 720,
                        "maxWidth": 1280,
                        "audio": false,
                        "maxFPS": 24,
                        "debug": true
                    }
                }
            ],
            "platform": "CameraUI"
        }`

![Screenshot from 2021-03-02 09-15-59](https://user-images.githubusercontent.com/11315372/109593962-f80dbe00-7b37-11eb-99ec-e0fa7cf7653e.png)

![Screenshot from 2021-03-02 09-02-32](https://user-images.githubusercontent.com/11315372/109592899-11ae0600-7b36-11eb-95b5-16cc27e5c032.png)

**Environment**
- Node.js Version: v10.21
- Homebridge Version: v1.1.7
- Camera UI Version: v3.1.5
- Operating System: Ubuntu 20.04
- Browser: Chromium

**Comment by SeydX** [comment]
@rashmendis 

does it work if you give the camera source a port? 

The ping takes 554 as default port to check if a camera is online/offline if no port is given in source.

**Comment by SeydX** [comment]
Fixed with v3.2.2

**Comment by shahzadgodil** [comment]
Hello,
 
I have homebridge-camera-ui v3.3.0 (2021-03-22) but I am still getting this same error.
https://tinyurl.com/yelyfezp

Thanks
Shahzad Godil
